### ISSUE TITLE
subMenu能否支持mode配置

### ISSUE THREAD

**Issue by vonxq** [react-component/menu#103]
项目应用中，一二级菜单直接inline展开，但三级菜单过长则希望可以以vertical形式显示。多级的vertical菜单容易误操作，还是希望菜单中能混用mode，最好是submenu自带mode属性

**Comment by benjycui** [comment]
这样交互得多乱。。

**Comment by vonxq** [comment]
@benjycui 感觉还好啊，我们三级菜单内容比较多，如果直接inline平铺的话太长了，也不好找，如果直接vertical在外面会清晰很多

**Comment by picodoth** [comment]
closing for no new activity
