### ISSUE TITLE
React.createElement: type is invalid

### ISSUE THREAD

**Issue by mijikim** [react-component/menu#107]
Hello,

I am seeing below error when I am trying to render a very simple menu. I can't seem to figure out why this is occurring.  I made sure that rc-menu was getting imported properly as well. Any ideas?

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object

Versions: 
    "react": "15.6.0",
    "react-dom": "15.4.1",
    "rc-menu": "6.2.0",

```
import Menu, {MenuItem} from 'rc-menu';
render() {
<div>
  <Menu>
    <MenuItem>1</MenuItem>
  </Menu>
</div>
}
```

**Comment by benjycui** [comment]
http://react-component.github.io/menu/examples/antd.html
