### ISSUE TITLE
MenuMixin.js 

### ISSUE THREAD

**Issue by logwood** [react-component/menu#109]
MenuMixin.js  168行在 菜单选中的情况下会响应 onKeyDown实际上， 实际上从控制台看 MenuItem对象中没有这个onKeyDown 属性，会报错。
这样修改下就解决了`if (obj && obj.props.active && obj.onKeyDown) {` 不知道是否正确

**Comment by afc163** [comment]
来个 PR ？

**Comment by logwood** [comment]
查了下代码 我本地npm安装MenuMixin.js 的在168行，你们仓库里面在124 行 我就不提PR了。
