### ISSUE TITLE
Link in MenuItem doesn't work

### ISSUE THREAD

**Issue by deammer** [react-component/menu#110]
Hi!

I'm trying to use a ReactRouter Link within a MenuItem, like so:

```
<Menu>
    <SubMenu>...</SubMenu>
    <MenuItem>
        <Link to="/login">Log In</Link>
    </MenuItem>
</Menu>
```

The problem is that the _first time_ I click on that Link, I get redirected to `/item_1`, instead of `/login`. Now if I click on the link _again_, I will get to my `/login` page.

**Comment by benjycui** [comment]
Please provide a re-producible demo: https://u.ant.design/codesandbox-repro

**Comment by deammer** [comment]
Closing this because the problem was in my implementation. Thanks!
