### ISSUE TITLE
Sub sub menu position

### ISSUE THREAD

**Issue by dana2208** [react-component/menu#114]
Hi,

There is an issue with the position of the sub sub menu (the menu is with mode vertical-right because of the language but the bug exists on the regular positioning).

When there is enough place on the left, it all opens on the left, which is OK:
![right](https://user-images.githubusercontent.com/10193337/34375391-fd84bb54-eaee-11e7-8517-a1968b4645b3.png)

When there is not enough place on the left for the sub sub menu it opens on the right, which is OK:
![middle](https://user-images.githubusercontent.com/10193337/34375390-fd3beb40-eaee-11e7-9d29-6c13b44fe708.png)

But when there is not enough place for the sub menu to open on the left, it opens on the right (which is OK) but then the sub sub menu opens on the left instead of the right:
![left](https://user-images.githubusercontent.com/10193337/34375389-fce25b84-eaee-11e7-93b3-551b08020ef2.png)

Can you tell me if there is a solution that I should implement or should you fix this?

Thank you

**Comment by benjycui** [comment]
Please provide a fullscreen screenshot, so that I can know where you place the menu.

**Comment by dana2208** [comment]
![context-menu](https://user-images.githubusercontent.com/10193337/34512484-7f65b656-f06b-11e7-908b-bdd5a3456189.png)

**Comment by benjycui** [comment]
In your use case, you should use `Menu[mode=vertical-left]`

**Comment by benjycui** [comment]
See: https://github.com/react-component/menu#menu-props

**Comment by dana2208** [comment]
Hi,

I have today the menu on position vertical-right.
Anyway I tried to put your menu on vertical-left and here is what I have:
![context-menu-vertical-left](https://user-images.githubusercontent.com/10193337/34554274-0774ef36-f124-11e7-9854-bebfc6e393ec.png)
It is not good since I need to open it on the right (my language is right to left). Therefore vertical-right was the right choice.
And anyway on the left it is still not OK when opening the sub-sub-menu close  to the right of the screen, it still opens on the menu instead of on the other side:
![context-menu-vertical-left-open-on-the right](https://user-images.githubusercontent.com/10193337/34554338-4c382f84-f124-11e7-9623-a2688740a9da.png)
This is the same issue as I have with vertical-left.

Thanks

**Comment by benjycui** [comment]
You need to calculate the mode(vertical-left or vertical-right) when you show the menu.
