### ISSUE TITLE
click outside to close menu

### ISSUE THREAD

**Issue by sht5** [react-component/menu#117]
there is no way to realize when someone clicked outside the component to close it.
there is not even a property to allow showing\not showing the component.
there is a component called react-click-outside which can be easily added to implement this functionality

**Comment by yesmeck** [comment]
Use `openKeys` to control menu.

**Comment by Hurtak** [comment]
Hi @yesmeck,

AFAIK openKeys only controls opened state of certain menu items, but it does not solve the problem of detecting if click was inside or outside the menu component. We cannot use react-click-outside because their html is outside of the main menu component.
