### ISSUE TITLE
6.2.7最新版本，存在键盘keyup和keydown Bug

### ISSUE THREAD

**Issue by xwzpp** [react-component/menu#126]
当我在使用rc-select@7.7.6的时候，我发现使用键盘keyup和keydown的时候，滚动条不随之改动，排查发现其依赖的rc-menu的版本为6.2.7，当我测试换成6.2.6后，该bug消失。

是不是最新的版本改动了滚动的逻辑？

**Comment by xwzpp** [comment]
+1

**Comment by yesmeck** [comment]
Fixed in 6.2.8
