### ISSUE TITLE
选中后，active 状态消失

### ISSUE THREAD

**Issue by afc163** [react-component/menu#13]
active 是 hover 中的状态，目前选中后，hover 状态会消失。**需要重新移出移入后才能激活 active**。

`active` 选中 => `selected`

选中后，hover 状态应该保持。

`active` 选中 => `active selected`

**Comment by yiminghe** [comment]
active 就是当前交互状态，选中和当前交互没有关系

**Comment by afc163** [comment]
现在选中之后，貌似会把 `当前交互状态` 给去掉。如果没关系的话，应该不影响的吧。

**Comment by afc163** [comment]
![](https://t.alipayobjects.com/images/rmsweb/T1g0NhXa8lXXXXXXXX.gif)
