### ISSUE TITLE
求助: 打包报错 getDefaultProps is only used on classic React

### ISSUE THREAD

**Issue by zjxpcyc** [react-component/menu#130]
```bash
Error: Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static pr  operty named `defaultProps` instead.
```

环境:
`win10 x64`
`node v8.7.0` 
`npm 5.4.2`
框架使用 [react-static](https://github.com/nozzle/react-static) 。
执行框架打包命令 `yarn build` 就报上面的错误。

如果我把使用 `rc-menu` 的地方注释掉，就能正常打包。

**Comment by chenshuai2144** [comment]
你是不是使用了React.createClass？

**Comment by zjxpcyc** [comment]
没有，在我使用 rc-menu 的组件里面，我是 这样写的 
`export default class extends PureComponent`

**Comment by zjxpcyc** [comment]
@picodoth 帮忙看看呢

**Comment by rayyee** [comment]
React 16 之后就有这个问题

**Comment by picodoth** [comment]
@zjxpcyc 不好意思才看到
https://github.com/react-component/menu/pull/133 应该能解决这个问题把

**Comment by picodoth** [comment]
奇怪，menu里面已经没有getDefaultProps了。。

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/issues/3649#issuecomment-311030696

**Comment by echizen** [comment]
<img width="643" alt="1ff8606c-fe3f-4758-a0a7-103fe42d2470" src="https://user-images.githubusercontent.com/5587105/41830177-f21b049c-7871-11e8-8fc2-03c871124947.png">

还有种情况，从某个版本开始create-react-class里加了以上判断，所以检查下是否你的develop环境的`process.env.NODE_ENV`变量没设置正确

**Comment by zlv-thisF** [comment]
遇到了这个问题，但是还是没有理解，确实如代码显示的情况，我在production环境，没有warnning；
但是在其他环境我没有使用getDefaultProps，看了下warning来自rc-tabs和rc-menu，我没有用cdn的antd.min.js或者antd.js.   现在test环境 stage环境都是waring。。。    实在不知道怎么解决 @echizen
