### ISSUE TITLE
improve responsiveness for horizontal menu mode

### ISSUE THREAD

**Issue by picodoth** [react-component/menu#148]
We need to improve responsiveness for horizontal menu mode. (ref:  https://github.com/ant-design/ant-design-pro/issues/717#issuecomment-392821583).

**What's the problem:**
![overflow](https://user-images.githubusercontent.com/1731837/40701790-e84155ee-6411-11e8-9db4-ef8b75e330f1.png)
As the above pic shows, the items will overflow to next line in horizontal mode if the space is not enough.

**What's the proposed solution:**
For horizontal mode, we need to provide a overflow hidden option, the overflowed items will be stacked into a 'more' tab, and clicking on the more tab will show a dropdown with all the hidden items.

**Comment by picodoth** [comment]
@afc163 @chenshuai2144 时间的花很紧急么？

**Comment by chenshuai2144** [comment]
Deadline 比较松 看你自己了

**Comment by picodoth** [comment]
7.2.0
