### ISSUE TITLE
Demo Page Failing

### ISSUE THREAD

**Issue by john-osullivan** [react-component/menu#15]
The [demo page](http://docs.spmjs.io/rc-menu/latest/examples/index.html#demo) doesn't have any working examples of this plug-in.  When I checked the console, it seemed to be an error with how React was defined:

`Uncaught TypeError: Cannot read property 'createClass' of undefined`

Inspecting the code led me to this line in Menu.js:

`var React = window.window.React;`

Fixing that could be enough to restore functionality.  An additional issue is that when I tried to inspect with React dev-tools, it complained saying the current version of React was outdated.

`You are using a version of React with limited support in this version of the devtools.
Please upgrade to use at least 0.13, or you can downgrade to use the old version of the devtools:
instructions here https://github.com/facebook/react-devtools/tree/devtools-next#how-do-i-use-this-for-react--013`

Any chance you can update this plug-in?  The nested menus look great, I'd love to use them!

**Comment by yiminghe** [comment]
see readme, demo is at http://react-component.github.io/menu/examples/

**Comment by john-osullivan** [comment]
That url redirects back to http://react-component.github.io/menu/ .
