### ISSUE TITLE
Menu Icons

### ISSUE THREAD

**Issue by junste** [react-component/menu#150]
Hi,

Is it possible to provide functionality for adding an icon on the left hand side in menu items and sub menus?

Regards,
Stefan

![menu](https://user-images.githubusercontent.com/1788911/40776410-f3d42f1c-64ca-11e8-9e35-5035f1d6aa5b.png)

**Comment by picodoth** [comment]
Menu is designed with composition in mind, you can always add icon directly, i.e. something like this:
```javascript
      <Menu>
        <MenuItem key="mail">
          <Icon type="mail" />Navigation One
        </Menu.Item>
        <Menu.Item key="app">
          <Icon type="appstore" />Navigation Two
        </Menu.Item>
```
