### ISSUE TITLE
Custom styling

### ISSUE THREAD

**Issue by junste** [react-component/menu#152]
Hi,

I want to set a custom style to my sub menus and my menu items. As for the menu items, everything works fine. However, when I set a different hover background-color on the sub menus, your light blue standard background-color remains. The sub menus should have the same grey hover color as the menu items in my example. Please se attached file.

Regards,
Stefan

![customstyling](https://user-images.githubusercontent.com/1788911/40838496-bb4e38f2-659e-11e8-83cd-4c4c343c5f9d.png)

**Comment by junste** [comment]
I use Fela for resolving styling classes into a variable named **subMenuClasses**, so there are a bunch of classes added to the sub menu component. My code is pretty straight forward:
`<SubMenu className={subMenuClasses} title={item.props.title} key={item.id}>{subResult}</SubMenu>`, where in this particular case, the classes added are: 'r u w x y', where classes x:hover and y:hover set the following styles: x:hover - color: #888 and y:hover - background-color: #f0f0f0.
As you can see, the browser inspector actually says that these classes are active, and the x:hover indeed is. However, the light blue color is still there. Perhaps it has something to do with the fact that classes **rc-menu-submenu-open** and **rc-menu-submenu-active** are resolved after my custom classes? I hope this can help.

Regards,
Stefan

![submenu_classes](https://user-images.githubusercontent.com/1788911/41153613-84022470-6b17-11e8-8bfb-cce7b4ce058a.png)

**Comment by picodoth** [comment]
I think it's just because the default color rule is more strict: https://github.com/react-component/menu/blob/master/assets/index.less#L125, you have to make your style customization targeting on more specific node.

**Comment by picodoth** [comment]
This is not an issue
