### ISSUE TITLE
subMenu展开的所有子菜单可以全部在左边逐级展开吗，现在是默认逐级在右边展开的

### ISSUE THREAD

**Issue by jinCreat** [react-component/menu#154]
使用mode="vertical-right"的话menuItem的排列会变为垂直方向，我希望是水平方向的排列，展开的subMenu菜单可以往左侧逐级展开

**Comment by jinCreat** [comment]
使用mode="vertical-right"的话menuItem的排列会变为垂直方向，我希望是水平方向的排列，展开的subMenu菜单可以往左侧逐级展开

**Comment by picodoth** [comment]
@jinCreat 我只看了issue title 没认真看你的第一条留言。现在 `vertical-right` 就是作伴逐级展开啊，默认右边逐级展开是 `vertical`

> 我希望是水平方向的排列

这个地方我不太理解，你是说 Menu 上用 `mode="horizontal"` 但是子菜单逐级向左边展开？

**Comment by picodoth** [comment]
7.2.0 released
