### ISSUE TITLE
what metod i can do 2-3 colums submenu?

### ISSUE THREAD

**Issue by romanown** [react-component/menu#160]
in the issue #158 Do you offer to put another menu in the desired menu item. 
I set the menu as a submenu. as you suggested. but it doesn't work.
is it possible to change the rc-menu component so that it can make several columns? do the same as in the example shown in html.

**Comment by picodoth** [comment]
@romanown we don't have this requirement, and it sounds like a very rare case. Do you want to provide a codepan/codesandbox link so I can see if I could offer help.

**Comment by romanown** [comment]
thus, the menu will become more functional and you can show the product in the menu. if this feature is available in the module, it will find its fans. this way Your menu will be the best.

**Comment by picodoth** [comment]
The problem is that <MenuItem> can contain any react node, it's still doable via:
```
<Menu>
  <SubMenu title='product overview'>
    <MenuItem>
       <Menu>
       </Menu>
       <Menu>
       </Menu>
    </MenuItem>
  </SubMenu>
</Menu>
```

If this doesn't work we need to fix it.

**Comment by picodoth** [comment]
@romanown you can do something like https://codesandbox.io/s/ywkjnvx5y1

Is that not working for you?

**Comment by romanown** [comment]
Thanks. I did not. but the submenu starts from the parent item a it is necessary to from the beginning of the menu. and when you add a picture there is an error. 
img is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.
 https://codesandbox.io/s/wqk74z4q88

**Comment by romanown** [comment]
thank You very match

**Comment by romanown** [comment]
but the submenu starts from the parent item a it is necessary to from the beginning of the menu.

**Comment by picodoth** [comment]
@romanown it's a very customized behavior, we're not thinking to support this right now.

**Comment by romanown** [comment]
thank you very much for your help. I hope you'll do it someday.
