### ISSUE TITLE
customising colors and sizes

### ISSUE THREAD

**Issue by romanown** [react-component/menu#163]
I really liked your module. sorry in the process of using the module there are new questions and tasks. how can I change the colors of text, background, hover, menu items and submenus? you also need to have different colors in the menu titles and submenus and items. edit css file is very inconvenient. you also want to change the size of all the elements and margins. I want to do all this by passing parameters to the module.

**Comment by picodoth** [comment]
Everything inside menuItem and title is fully configurable. You can do whatever you want inside MenuItem/SubMenu Title.

**Comment by romanown** [comment]
give example please

**Comment by romanown** [comment]
do not working 
<SubMenu title={titleRight0} key="1">
		{menu[0].map((item, index) =>
          <MenuItem key={'1-' + index} style={{backgroundColor: '#2e8982cc'}}><Link to={item.to}> {item.title}</Link> </MenuItem>
        )}
      </SubMenu>
