### ISSUE TITLE
i can not align menuitems to center

### ISSUE THREAD

**Issue by romanown** [react-component/menu#164]
i am wraped the rc-menu the css blocks align-content:center. but items aligned to left as default.

**Comment by picodoth** [comment]
a codesandbox link would be helpful

**Comment by romanown** [comment]
full example https://codesandbox.io/s/zkj18410np

**Comment by romanown** [comment]
mobile screen realy 320px

**Comment by picodoth** [comment]
Inline menu is not supposed to be used in this way, consider using http://react-component.github.io/collapse/

**Comment by picodoth** [comment]
If you want to align item in the middle and removed the left padding, you can pass in inlineIndent to be 0.

**Comment by romanown** [comment]
i am do not understand

**Comment by picodoth** [comment]
https://github.com/react-component/menu/blob/df2bc2b7fc35f25002db7c334fe218dbfd7c4e95/src/MenuItem.jsx#L182

**Comment by romanown** [comment]
thank You
