### ISSUE TITLE
can it do as Accordion?

### ISSUE THREAD

**Issue by romanown** [react-component/menu#165]
as http://jsfiddle.net/romanown/q37mvr54/19/ second examlpe for reopening https://designmodo.com/demo/css3accordionmenu/

**Comment by romanown** [comment]
I make a menu for my website with the responsive layout to be convenient on a desktop and on a mobile phone to watch. so I suggest you do these functions in Your module. when you have added the functions I have listed, this module will be the best.

**Comment by picodoth** [comment]
see http://react-component.github.io/collapse/

**Comment by romanown** [comment]
thank You but it have another purpose. accordeon menu is diffrent from the collapse

**Comment by romanown** [comment]
can You add collapse to menu?
