### ISSUE TITLE
divider props

### ISSUE THREAD

**Issue by romanown** [react-component/menu#168]
need divider props, i need change the color of divider.
https://codesandbox.io/s/o76oqwz1xq
not working
<Divider style={{
                    backgroundColor: "red",
                    color: 'blue', 
                  }} />

**Comment by picodoth** [comment]
looking at the src code, we didn't inherit any style. You can do through classname: https://github.com/react-component/menu/blob/master/src/Divider.jsx. PR will be appreciated.

**Comment by romanown** [comment]
i am do it but divider sametime is white/
https://codesandbox.io/s/2jxw196nj0

**Comment by picodoth** [comment]
using it as `className` not styles. You're using style as className

**Comment by romanown** [comment]
i can not. give me the example please.

**Comment by romanown** [comment]
i am wrote the className but it is do not working https://codesandbox.io/s/2jxw196nj0

**Comment by romanown** [comment]
Thanks. but it is very inconvenient to make everything in css. inline is more convenient.

**Comment by romanown** [comment]
in order not to open a new record I will write here. I try to use icons but writes that an error. https://codesandbox.io/s/61q92991mz

**Comment by picodoth** [comment]
that's really a stackoverflow issue. it's not a menu problem

**Comment by romanown** [comment]
i am tryed inline but do not effect https://codesandbox.io/s/9z3zrz3814

**Comment by picodoth** [comment]
it's not merged/published yet..

**Comment by romanown** [comment]
It is about divider 

> it's not merged/published yet..
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 
Roman

**Comment by romanown** [comment]
thank You. i am waiting.

**Comment by picodoth** [comment]
7.2.0 released

**Comment by romanown** [comment]
thank You

**Comment by romanown** [comment]
but inline do not effect https://codesandbox.io/s/9z3zrz3814

**Comment by romanown** [comment]
7.2.0 released but divider props do not working.

**Comment by picodoth** [comment]
unfortunately we reverted that change in 7.2.6 If you need that and you're not using react@15, you can lock rc-menu version @ 7.2.5. We're planning to redo that work in 2 weeks.
