### ISSUE TITLE
change submenu-arrow

### ISSUE THREAD

**Issue by romanown** [react-component/menu#169]
1. haw i can change picture of the submenu-arrow
2. change degrees of rotation
submenu-arrow {
  transform: rotate(?deg)
https://codesandbox.io/s/o76oqwz1xq

**Comment by picodoth** [comment]
1. you'll have to overwrite https://github.com/react-component/menu/blob/master/assets/index.less#L148

2. https://codesandbox.io/s/vq01n89ozy

**Comment by romanown** [comment]
thank You.

**Comment by romanown** [comment]
haw i can change picture of the submenu-arrow to big white **>**? i can not found this.
