### ISSUE TITLE
compatibility is breaking using React.Fragment

### ISSUE THREAD

**Issue by eternalsky** [react-component/menu#177]
在 7.2.5 里引入了 React.Fragment(https://github.com/react-component/menu/blob/master/src/DOMWrap.jsx#L149),  这使得组件的兼容性发生了变化，原有（7.2.5 之前）的兼容性是可以到 0.14.9 及以上，新版本中 Fragment 只存在于 React16，兼容性提升到了 16 的版本，但在版本号里没有体现，这导致一系列依赖该组件的业务重新打包后挂掉了。

**Comment by yesmeck** [comment]
已经回滚了相关的 feature。
