### ISSUE TITLE
Menu set selectedKeys. Hope to auto expand parent SubMenu

### ISSUE THREAD

**Issue by picodoth** [react-component/menu#187]
If the selectedKeys value is set, the parent menu is not expanded and is meaningless to the user.

What does the proposed API look like?
autoExpandParent={true}

ref: https://github.com/ant-design/ant-design/issues/11764

**Comment by eggnita** [comment]
agree with this, it seems that also there isn't any function available in the Submenu API to expand it from outside.  @picodoth have you found any workaround for this? To auto simulate a click on that seems a bit to much to achieve this.

**Comment by eggnita** [comment]
@picodoth yup, that works, but the problem is that the parent cannot be collapsed anymore if you provide openKeys
