### ISSUE TITLE
set 'defaultOpenKeys', but it does not work

### ISSUE THREAD

**Issue by Jackie1210** [react-component/menu#188]
[codesandbox](https://codesandbox.io/s/mq50ok96yx)

The url above is an example from this repo. I want to set initial openKeys so that the tree will work like i want.Did i write something incorrectly? Thank you for your help.

**Comment by picodoth** [comment]
Hi Jackie, isn't http://react-component.github.io/menu/examples/selectedKeys.html working for you? I think your link is not processing .less file correctly

**Comment by picodoth** [comment]
close due to inactivity
