### ISSUE TITLE
refactor: use rc-trigger for SubMenuItem

### ISSUE THREAD

**Issue by yiminghe** [react-component/menu#19]
to popup sub menu

**Comment by yiminghe** [comment]
https://css-tricks.com/popping-hidden-overflow/

**Comment by liujhfly** [comment]
这个问题是导航菜单在浏览器下端时，弹出的二级菜单被浏览器遮挡，与设计overflow没有关系吧，应该是改变弹出二层菜单css样式的top值，可是如何在二级菜单弹出时，能获取二级菜单的Dom并改变top值呢？

**Comment by benjycui** [comment]
重构为 rc-trigger 的话，同时也能解决这个问题 https://github.com/react-component/menu/issues/25

@liujhfly rc-trigger 会自动选择适合的位置弹出。

**Comment by benjycui** [comment]
这个重构也将能解决以下问题：

* render PopupMenu to document.body https://github.com/react-component/menu/issues/49
* 能否支持屏幕边缘的多级menu可以出现在左侧 https://github.com/react-component/menu/issues/53
* Scrollable Menu with max-height https://github.com/react-component/menu/issues/25
* Debounced open https://github.com/react-component/menu/issues/24
* Allow setting container for pop menu https://github.com/react-component/menu/issues/73

**Comment by ascoders** [comment]
这个重构非常好，特别是父级不可控，而且含有 `overflow:hidden` 时，dom 节点挪到外面才是正解。

**Comment by benjycui** [comment]
@ascoders 来一个 PR 😄

**Comment by vipcxj** [comment]
原来还没解决啊，那是不是说暂时没救了？或者有没有什么在不改Menu源码前提下的workround？

**Comment by zachguo** [comment]
目前`antd Menu`碰到的两个问题都追溯到这里 https://github.com/ant-design/ant-design/issues/2837 和 https://github.com/ant-design/ant-design/issues/6589 
可惜重构这活作为外人也帮不上什么忙。。😭
