### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of undefined 

### ISSUE THREAD

**Issue by boychina** [react-component/menu#190]
antd 版本升级到 3.9.0， _rc_menu 版本升级到 7.4.1。
 node_modules/_rc-menu@7.4.1@rc-menu/es/util.js:55 出现出现报错，_Cannot read property 'getBoundingClientRect' of undefined_
![image](https://user-images.githubusercontent.com/20528499/44971611-d5ab8180-af88-11e8-95f3-b6836a05c0af.png)

antd 3.8.4 _rc_menu 7.0.5 中没有 getWidth 这个方法，不存在这个问题。

环境信息：
tnpm@6.5.0 
npm@6.4.0 
node@8.11.1
npminstall@3.11.0
win32 x64 6.1.7601

**Comment by afc163** [comment]
能给个重现么 http://codesandbox.io/

**Comment by picodoth** [comment]
沟通过了，现在问题貌似解决了，有需要 reopening

**Comment by boychina** [comment]
新版本已经修复了这个问题，谢谢你们的工作！
