### ISSUE TITLE
Horizontal menu overflow

### ISSUE THREAD

**Issue by MiroslavPetrik** [react-component/menu#191]
I use menu in navigation aligned to right. When the collapsing/oveflow is not happening, I have an empty item on the right side with `visibility: hidden`.

![screenshot from 2018-09-03 10-41-06](https://user-images.githubusercontent.com/38855190/44976576-e7c7f880-af65-11e8-8110-5368da1e052b.png)

Instead, it would be better to `display: none` so it does not occupy any space.
Maybe even option to disable the `overflowedIndicator`. Setting it to `null` still does not prevent it's parent to be rendered and occupy space.

**Comment by picodoth** [comment]
Hi @MiroslavPetrik thanks for your feedback. The extra placeholder was used for calculating the actual space would be occupied by the overflow indicator.

I just made a fix to set the width to be 0 after calculation. The space occupation propblem should be gone in 7.4.4.

It might be a good idea to make this behavior optional.

**Comment by picodoth** [comment]
closing now, reopening as needed
