### ISSUE TITLE
Collapsed MenuItems do not rerender when disabled attribute changes

### ISSUE THREAD

**Issue by goodoldneon** [react-component/menu#193]
This is tough to explain, but I'll try.

I conditionally disable MenuItems using `state`. When a `MenuItem` is collapsed (due to narrow window width), it doesn't rerender when `state` says it should be enabled.

In the following image, the "Hello" `MenuItem` was `disabled={true}` on mount. I clicked the button to change it to `disabled={false}`, but it's still disabled.

<img width="467" alt="screen shot 2018-09-12 at 4 21 50 pm" src="https://user-images.githubusercontent.com/20100586/45451194-5284dc80-b6a8-11e8-9f82-417d4bbb4473.png">

This issue doesn't happen if at least one `MenuItem` prints the changed `state` item. Pretty bizarre. The following image shows the exact same situation as the previous image, but I've added a `MenuItem` which prints the changed `state` (`<MenuItem>{isEnabled + ''}</MenuItem>`).

<img width="470" alt="screen shot 2018-09-12 at 4 22 12 pm" src="https://user-images.githubusercontent.com/20100586/45451197-54e73680-b6a8-11e8-8ccf-829e5d87290f.png">

Here's my example code:

```jsx
class Index extends React.Component {
  constructor() {
    super();

    this.state = {
      isEnabled: false,
    };
  }

  render() {
    const { isEnabled } = this.state;

    return (
      <div>
        <Menu mode="horizontal">
          <SubMenu title="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA">
            <MenuItem disabled={!isEnabled}>2-1</MenuItem>
          </SubMenu>

          <MenuItem disabled={!isEnabled} onClick={console.log}>
            Hello
          </MenuItem>

          {/*
            * If the above MenuItem is collapsed (because window width is very narrow), then the following MenuItem is necessary to force rerender.
          */}
          <MenuItem>{isEnabled + ''}</MenuItem>
        </Menu>
        <button onClick={() => this.setState({ isEnabled: !isEnabled })}>
          Click to {isEnabled ? 'Disable' : 'Enable'}
        </button>
        The Hello menu item should be {isEnabled ? 'enabled' : 'disabled'}.
      </div>
    );
  }
}
```

**Comment by picodoth** [comment]
Thanks for reporting, will take a look later today.

**Comment by goodoldneon** [comment]
Created a PR to fix this.

I noticed that resizing caused the overflowed submenu to rerender. In `DOMWrap.handleResize()`, `this.overflowedItems` is rebuilt from `this.props.children`. So to solve this issue, I used the same rebuild code in the `DOMWrap.renderChildren()` method.
