### ISSUE TITLE
"Overflowed" menu items still occupy space

### ISSUE THREAD

**Issue by yp** [react-component/menu#199]
I am using the menu in horizontal mode as a main navigation topbar. When items overflow, they are correctly placed in the "overflowed" submenu, but they are still occupying space in the topbar. Is `visibility: hidden` needed?

Before:
![before](https://user-images.githubusercontent.com/275483/45818595-723c8600-bce2-11e8-8dfb-99d1f6a17d73.png)

After:
![after](https://user-images.githubusercontent.com/275483/45818616-7e284800-bce2-11e8-9239-26fb8ef8ac3f.png)

Please notice the bottom horizontal scroll bar.

I am using version 7.4.8.

**Comment by picodoth** [comment]
can you provide a link to reproduce? Did you set overflow: hidden on menu ul?

**Comment by yp** [comment]
Sure. Here is the link: https://codepen.io/yps/pen/PdLZQg

As far as I can tell, `overflow: hidden` is not set on `<ul>`. Setting it partially solves the problem. Indeed, if you click on the "..." menu and then hover over one of the overflowed items, the horizontal scrollbar appears.

**Comment by picodoth** [comment]
@yp somehow antd@3.10.2 didn't pickup latest rc-menu version. Can you reproduce in your local environment by reinstall antd?

**Comment by picodoth** [comment]
The latest rc-menu should be at 7.4.16

**Comment by yp** [comment]
Yes, I confirm that on my local environment it correctly sets `display: none`.
Shouldn't the same mechanism be applied to the overflowed indicator? Now it has `visibility: hidden; position: absolute; width: 0`, but its child `div.ant-menu-submenu-title` still occupies space.

**Comment by picodoth** [comment]
@yp u'r correct, thanks for the suggestion. Addressed in 1870b7943426f2357f74759b2e843707d94a3894. Does it cause any issue?

**Comment by yp** [comment]
Thanks.
In my case, since I do no have horizontal padding, the overflowed indicator still occupies space causing the appearance of the scrollbar.
I wait for the release.
Thanks again.
