### ISSUE TITLE
Sub menu arrow not loading in Chrome or Firefox

### ISSUE THREAD

**Issue by iansullivan88** [react-component/menu#206]
The css requests the 'FontAwesome' font family from 'cdn.bootcss.com'. This cdn just redirects to a cloudflare url which causes the following CORS error in Chrome:

`Redirect from 'https://cdn.bootcss.com/font-awesome/4.2.0/fonts/fontawesome-webfont.woff?v=4.2.0' to 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/fonts/fontawesome-webfont.woff' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.`

As far as I can see, the only use of FontAwesome is to provide a right arrow icon. Could a right arrow be included in the library itself or could the arrow be created with CSS? Or, could cdnjs.cloudflare.com be referenced directly without going to cdn.bootcss.com?

**Comment by picodoth** [comment]
fixed in 7.4.13

**Comment by iansullivan88** [comment]
> fixed in 7.4.13

Thank you!
