### ISSUE TITLE
Click event triggered twice when items are overflowed into submenu

### ISSUE THREAD

**Issue by goodoldneon** [react-component/menu#209]
When items are overflowed into a submenu (i.e. the "..." menu), their click events are triggered twice. This can be seen in `examples/antd`.

This issue appears to be caused by `newChildProps.onClick()` in `SubPopupMenu.renderCommonMenuItem()`:

```js
onClick: (e) => {
    (childProps.onClick || noop)(e);
    this.onClick(e);
},
```

The double-event issue goes away when I delete `(childProps.onClick || noop)(e)`. What's the purpose of this line?

**Comment by picodoth** [comment]
fixed in 9b860c56675f248967ff3a7a9ff6b2df09f491ab and available in 7.4.15
