### ISSUE TITLE
Menu theming

### ISSUE THREAD

**Issue by davejacobs** [react-component/menu#21]
What's the recommended way to implement another theme for the menu?

**Comment by yiminghe** [comment]
create another css

**Comment by davejacobs** [comment]
Thanks. One suggestion I have would be great to split the stylesheet into a theme section and a structural section (positioning of menus, show-hide, etc.) and also to document what the class structure is for each menu type.

**Comment by yiminghe** [comment]
welcome pr

**Comment by benjycui** [comment]
Anyone can create PR for this feature anytime, I close this issue just because we don't need this feature and will not spend time on it.
