### ISSUE TITLE
Importing the css file produces error

### ISSUE THREAD

**Issue by purezen** [react-component/menu#23]
I am using https://github.com/gaearon/react-transform-boilerplate for my app. When I include the css file using

    import 'rc-menu/assets/index.css';

, I get the following error:

```
ERROR in ./~/rc-menu/assets/index.css
Module parse failed: /home/purezen/workspace/react-transform-boilerplate/node_modules/rc-menu/assets/index.css Line 1: Unexpected token .
You may need an appropriate loader to handle this file type.
| .rc-menu {
|   outline: none;
|   margin-bottom: 0;
 @ ./src/Header.js 30:0-35
```

Have installed less-loader and patched the webpack config as well.

**Comment by yiminghe** [comment]
refer: https://github.com/react-component/rc-tools/blob/835ceb75ff14734d86f867ddd09365ee3c9feddd/lib/getWebpackCommon.js#L67
