### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Enalmada** [react-component/menu#232]
during jest test (works fine in normal usage), ant design horizontal menu is throwing  ` TypeError: Cannot read property 'split' of undefined` here:
```
  at node_modules/rc-menu/lib/DOMWrap.js:82:31
          at Array.filter (<anonymous>)
      at DOMWrap._this.getMenuItemNodes (node_modules/rc-menu/lib/DOMWrap.js:81:41)
      at DOMWrap._this.setChildrenWidthAndResize (node_modules/rc-menu/lib/DOMWrap.js:165:33)
      at DOMWrap.componentDidMount (node_modules/rc-menu/lib/DOMWrap.js:227:10)

```
https://github.com/react-component/menu/blob/master/src/DOMWrap.jsx#L77

The menu in my code has no explicit submenu items defined, its just a single level header menu....though when inspecting I see ant design adding a "ant-menu-submenu ant-menu-submenu-horizontal ant-menu-overflowed-submenu" with "display:none;" for no apparent reason. See the first example "Navigation One" here for an example: https://ant.design/components/menu 
```
<ul class="ant-menu ant-menu-light ant-menu-root ant-menu-horizontal" role="menu">
   <!-- Why is this empty submenu even here? -->
   <li class="ant-menu-submenu ant-menu-submenu-horizontal ant-menu-overflowed-submenu" role="menuitem" style="display: none;"><div class="ant-menu-submenu-title" aria-expanded="false" aria-haspopup="true"><span>···</span><i class="ant-menu-submenu-arrow"></i></div></li>
   <li class="ant-menu-item ant-menu-item-selected" role="menuitem"><i class="anticon anticon-mail"><svg viewBox="64 64 896 896" class="" data-icon="mail" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M928 160H96c-17.7 0-32 14.3-32 32v640c0 17.7 14.3 32 32 32h832c17.7 0 32-14.3 32-32V192c0-17.7-14.3-32-32-32zm-40 110.8V792H136V270.8l-27.6-21.5 39.3-50.5 42.8 33.3h643.1l42.8-33.3 39.3 50.5-27.7 21.5zM833.6 232L512 482 190.4 232l-42.8-33.3-39.3 50.5 27.6 21.5 341.6 265.6a55.99 55.99 0 0 0 68.7 0L888 270.8l27.6-21.5-39.3-50.5-42.7 33.2z"></path></svg></i>Navigation One</li>
   ...
```
Can rc-menu be optimized to not create display:none submenu elements if there are no submenu explicitly defined?  or is that an ant design issue? 

I am too new to understand why this error only happens during test but is there anything that you think could be done to prevent the `Cannot read property 'split' of undefined` in this case?  It seems related to submenu which I am not using so I am hoping some optimization somehow could avoid the problem entirely.

**Comment by picodoth** [comment]
`TypeError: Cannot read property 'split' of undefined`, seems like 'className' in not available in the mocked  dom node.

Can you tell me your exact Jest version? 

Wrt the submenu that is`display: none`, it's an implementation detail for doing overflowed menuItem in horizontal mode.

**Comment by Enalmada** [comment]
Here is the boiler plate project I am trying to create for the community that is having the problem so you can see the reproduction: https://github.com/Enalmada/next-reason-boilerplate

Jest: 23.6.0

I am using ant design which seems to use rc-menu so it is quite possible there is something they are doing that exposes this issue during tests?

**Comment by picodoth** [comment]
@Enalmada 
I got a different error in the repo while running `npm run test`

<img width="976" alt="screen shot 2018-12-27 at 7 49 26 pm" src="https://user-images.githubusercontent.com/1731837/50479265-a4abfc80-0a10-11e9-91a8-0a575d98e654.png">

It would be really nice if you can create a minimal example for reproducing it..

**Comment by picodoth** [comment]
I looked at JSDOM which is used by jest, it's saying 

> 
jsdom is a pure-JavaScript implementation of many web standards, notably the WHATWG DOM and HTML Standards

**Comment by Enalmada** [comment]
Sorry you are getting that unrelated error.  That "Element type is invalid" means some of the reasonml typesafe bindings don't match package.json dependency versions.  It is very strange the project would give that to you out of the box though....usually I only get it when trying to use a version of antd greater than 3.11.2.

I will create a simpler case without the reason-react.

**Comment by Enalmada** [comment]
I cut down the test case to remove superfluous reason-react in this branch "split": https://github.com/Enalmada/next-reason-boilerplate/tree/split

Basically if you try to run jest test on ant design horizontal menu you get the split error:
```
import {Menu} from "antd";
const Index = () => (
    <div>
        <h1>Split Test Fail Example</h1>
        <Menu
            mode="horizontal"
        >
            <Menu.Item key="mail">
                    Navigation One
            </Menu.Item>
            <Menu.Item key="app">
                Navigation Two
            </Menu.Item>
        </Menu>
    </div>
);
export default Index;
```

**Comment by Enalmada** [comment]
Here is the console.log of the node: https://gist.github.com/Enalmada/18f3ec03f1c5790bcd69007f5583c95a

Note it was circular, not sure if that is expected, so I had to do this to print it:
```
const JSON = require('circular-json');
...
console.log("node:" + JSON.stringify(node));
```
I tried doing an undefined check on the line and there is another split here:
https://github.com/react-component/menu/blob/master/src/DOMWrap.jsx#L161

Hopefully the simplified split branch above or the gist of the node error helps.  Let me know if there is anything else I can do to help!

**Comment by picodoth** [comment]
@Enalmada thanks，taking a look

**Comment by picodoth** [comment]
@Enalmada seems like it's caused by `createComponentWithPrerequisites`, which is using react-test-renderer. 

> rc component which antd deps on use some DOM native props. This means react-test-renderer can not handle that.

ref: https://github.com/ant-design/ant-design/issues/12439#issuecomment-428132092

**Comment by picodoth** [comment]
please consider using enzyme.

**Comment by Enalmada** [comment]
Switching react-test-renderer to enzyme seems to work!  Thank you for your help.

**Comment by nishant-dani** [comment]
Would be great if it could work with react-test-renderer as well.

**Comment by rwieruch** [comment]
@nishant-dani would you mind sharing your workaround here?

**Comment by nishant-dani** [comment]
@rwieruch - I have a class MenuTopLevel that wraps the Menu in its render.  
So I mocked it = jest.mock('./MenuTopLevel')

**Comment by rwieruch** [comment]
@nishant-dani okay, then it's basically the same as me.

I ran into more similar issues, but they are all related to UI components from [antd](https://ant.design/). Because react-testing-library isn't using jsdom, I switched to react-testing-library to get DOM support. All issues disappeared. I guess Enzyme works too.
