### ISSUE TITLE
Debounced open

### ISSUE THREAD

**Issue by rattrayalex** [react-component/menu#24]
Hi there, 

Great work on this. I'd like to be able to delay the opening of a menu by a small amount - say, 200ms - so that quick, unintentional mouseovers don't cause a menu to open. I don't _think_ this is currently possible, though I may be wrong. Chances are this would best be achieved with manual hooks to show/hide the menu and listen on mousenter/leave events, though I certainly wouldn't complain about a `delay` prop. 

Thoughts?

**Comment by yiminghe** [comment]
openDelay props is ok. 

welcome pr

**Comment by benjycui** [comment]
trace: https://github.com/react-component/menu/issues/19
