### ISSUE TITLE
Should rc-menu support space in JSX ?

### ISSUE THREAD

**Issue by banyudu** [react-component/menu#243]
Hi,  I found rc-menu doesn't support space in jsx.

```javascript
<Menu> {menuItems} </Menu>
```

fails with 

> TypeError
> Cannot read property 'disabled' of undefined

while 

```javascript
<Menu>{menuItems}</Menu>
```
works.

Is it a bug?

Live demo: https://codesandbox.io/s/vnpn8vvp33

**Comment by afc163** [comment]
fixed by https://github.com/react-component/menu/commit/b933ba9817d5130f206fb4e5416c360128e69604

https://codesandbox.io/s/1q4r7wzxq7
