### ISSUE TITLE
Scrollable Menu with max-height

### ISSUE THREAD

**Issue by rattrayalex** [react-component/menu#25]
Hi again,

This is a bit of a long shot but thought I'd throw it out there. It'd be really awesome to be able to have menus with `max-height` and `overflow-y: auto;` that support submenus. This works no-problem as long as a menu has no submenus, but the overflow swallows the children if you try to add a submenu. 

Note that this is a fundamental problem with this kind of approach. [Here is an article](https://css-tricks.com/popping-hidden-overflow/) outlining why this won't work. tl;dr, the submenu must be rendered as a sibling (or higher) to the scrollable menu, and positioned with javascript. Obviously, this would be a lot more involved than the current implementation. 

Thoughts?

Thanks!

**Comment by yiminghe** [comment]
Thanks,  [this method](https://css-tricks.com/popping-hidden-overflow/) is better indeed, we will consider it.

**Comment by maxmatthews** [comment]
Any updates on this? I need a scrollable submenu as well as wondering if there's any way to accomplish it?

**Comment by yiminghe** [comment]
can you make a pr?

**Comment by yiminghe** [comment]
@superRaytin

**Comment by benjycui** [comment]
Trace: https://github.com/react-component/menu/issues/19
