### ISSUE TITLE
Allow customizing ItemGroup title

### ISSUE THREAD

**Issue by atifsyedali** [react-component/menu#256]
# Problem
I have a use case where a user is types into a text box and a menu is shown with fuzzy-matched elements, such as:

Input: `A`
Output:

Menu X
-- Item **A**1
-- Item **A**2
-- Item **A**3

This works fine, because `Item A1`, `Item A2`, `Item A3` are all `Menu.Item` that I control with inner children.

However, I also want to match the groups, like so:

Input: `A`
Output:

Menu **A**
-- Item X
-- Item Y
-- Item Z

But I am unable to make **A** in `Menu A` bold because the Menu.ItemGroup only accepts a string `title`.

I suspect there might be other cases where such customization of groups are important, for example to icons to group titles.

# Proposal

In addition to `title`, allow an optional `titleNode` of type ReactNode which, if supplied, will be used to render as a child of the ItemGroup's div element instead of a plain `title` string.

**Comment by yesmeck** [comment]
I think you can pass ReactNode to `title` directly.

**Comment by atifsyedali** [comment]
Ah yes you can. Sorry for the trouble. Closing this issue.
