### ISSUE TITLE
index.css is not included in /assets for v7.4.30

### ISSUE THREAD

**Issue by gnoyixiang** [react-component/menu#288]
Hello, I updated to v7.4.30 and I got this error when importing /assets/index.css

Module not found: Can't resolve 'rc-menu/assets/index.css' 

Only the index.less file is included in /assets
Can the css file be added back?
I will use v7.4.29 for now until this is fixed.

Thanks!

**Comment by zombieJ** [comment]
Need volunteer to help on this.

ref: https://github.com/react-component/tree/issues/263#issuecomment-530800734

**Comment by zombieJ** [comment]
Update: https://unpkg.com/browse/rc-menu@7.4.31/assets/

**Comment by dsarfati** [comment]
This still doesn't seem to work when using CRA. During the yarn install process I see the assets folder but then it gets removed later on during `Cleaning Modules` phase.

**Comment by dsarfati** [comment]
Discovered that this is an issue with yarn and not CRA. The default/recommended `.yarnclean` file includes `assets`. I simply needed to add `!rc-menu/assets` to the end of the `.yarnclean` file so the css isn't removed.
