### ISSUE TITLE
SubMenu[title] active 状态没有消除

### ISSUE THREAD

**Issue by benjycui** [react-component/menu#30]
demo: http://ant.design/components/menu/#demo-theme

hover 在导航一上面，然后滑下到任意一个 Menu.Item，上面的 active 状态没有及时消除。

![image](https://cloud.githubusercontent.com/assets/3580607/14487393/d9ac902a-0194-11e6-92d8-f0ac07efca7d.png)

**Comment by yiminghe** [comment]
inline 应该清空上层 active 状态，试下 pr

**Comment by superRaytin** [comment]
@yiminghe OK，这个问题我尝试一并修复

**Comment by afc163** [comment]
@superRaytin 这个问题 antd 网站也遇到了。

**Comment by superRaytin** [comment]
嗯，我知道，争取这周末搞定 ✊
