### ISSUE TITLE
Warning about accessing DOM node props

### ISSUE THREAD

**Issue by davejacobs** [react-component/menu#38]
Heads up, this line is now throwing a warning for me:

https://github.com/react-component/menu/blob/master/src/MenuMixin.js#L169

The warning is: "ReactDOMComponent: Do not access .props of a DOM node; instead, recreate the props as `render` did originally or read the DOM properties/attributes directly from this node (e.g., this.refs.box.className). This DOM node was rendered by `Menu`."

I'm using React 0.14 and ReactDOM 0.14.

**Comment by yiminghe** [comment]
please provide a demo:  http://codepen.io/anon/pen/wGOWGW?editors=001
