### ISSUE TITLE
When using html tags inside Menu it throws errors: React does not recognize the `eventKey` prop on a DOM element.

### ISSUE THREAD

**Issue by Dorious** [react-component/menu#407]
I get an error while using normal html tags inside `<Menu>`:
React does not recognize the `eventKey` prop on a DOM element.....
React does not recognize the `warnKey` prop on a DOM element.....

Easy reproduce
```
<Menu>
   <div /> 
</Menu>
```

Funny but when you use React component it doens't have that problem, this doesn't throw anything:
```
const Comp = () = <div />

<Menu>
  <Comp />
</Menu>
```

![image](https://user-images.githubusercontent.com/2143349/121202107-53f18c80-c875-11eb-84e2-dc76d5048de1.png)

**Comment by ChromasIV** [comment]
Having the same issue...anyone had any luck?

**Comment by ChromasIV** [comment]
Seems that you need to use MenuItem as intended and if not exported right when under the Menu tag it will throw these issues. Hope that helps.

**Comment by zombieJ** [comment]
https://ant.design/components/menu/#Notes-for-developers

**Comment by mkuysunov** [comment]
I resolve this problem like this
`
const MenuHeader = (props) => (<div>yout code (JSX)</div>);
<Menu>
    <MenuHeader />
      yout code (JSX)
</Menu>
`

**Comment by chgo0506** [comment]
일진
