### ISSUE TITLE
inline menu item still active when selected change [version 9.x]

### ISSUE THREAD

**Issue by rpyoyo** [react-component/menu#422]
![QQ图片20210917111610](https://user-images.githubusercontent.com/4035181/133719028-5a16942a-31fc-47bf-96de-df7c09bbc834.png)

some menu item or sub menu item may remain active when i swith the menu from one to another.
it doesn't hanppen when use version 8.x

**Comment by carolinaknoll** [comment]
For anyone else having this error, the bug that is happening is that when we hover a menu item and it opens a new one, both of them cannot be closed by hovering out or clicking outside the component. 

I had the same issue and had to install an earlier version for it to work, which is `8.10.8`. 

I noticed that even by using the [single-menu example code](https://github.com/react-component/menu/blob/8.x/docs/examples/single.tsx), the bug still persisted and I had to rollback to the earlier version above.

**Comment by feibi** [comment]
Just like you

**Comment by ClementBenezech** [comment]
Same problem here. Had to reverse to 8.10.8 version as well. 

I'm thinking about switching libraries, since this has not been fixed in 8 month now, while multiple 9.X versions have been released. 

Haven't found an easy fix for this either. Sad :(

**Comment by dfbaskin** [comment]
Added a work-around in #437, if that is helpful.
