### ISSUE TITLE
Submenu not closing when mouse exits content.

### ISSUE THREAD

**Issue by ClementBenezech** [react-component/menu#437]
Hi all,

I'm opening a new issue even if this problem has already been reported here ( https://github.com/react-component/menu/issues/422#issue-998892311 ) in september 2021.

I'm posting this new ticket to help you identify the issue, and also to raise awareness 😄 as I'm sure this fix would benefit lots of people!

With every 9.X version, default settings, no fancy props, submenus will expand on hover but their popup never hides on cursor exit. 

To reproduce, just fork this sandbox: https://codesandbox.io/s/yu8mi

1) Check behavior with current 7.5.5 version as sandbox dependency => menus show up then hide on cursor exit.

2) Change RC-MENU version from 7.5.5 to 8.10.8 => Unchanged, menus show up then hide on cursor exit.

3) Then change to version "Anything equal or above 9.0" => Broken, menus do not hide on cursor exit anymore. 

I'm pretty sure this is unintended and is a major regression for RC-MENU compared to 8.X

Is there any chance this fix could be scheduled for the next 9.X minor release?

Thanks in advance for you help.

Clément

**Comment by ozee31** [comment]
i have the same problem

**Comment by dfbaskin** [comment]
A work-around seems to be setting `autoDestroy` as a default property so that it is passed to the trigger directly.  Not sure what other issues this might raise, though.

```ts
import Trigger from 'rc-trigger';
Trigger.defaultProps.autoDestroy = true;
```

It seems like the code in https://github.com/react-component/trigger/blob/master/src/index.tsx#L874 does not close the portals associated with SubMenu components:

```ts
      let portal: React.ReactElement;
      // prevent unmounting after it's rendered
      if (popupVisible || this.popupRef.current || forceRender) {
        portal = (
          <PortalComponent
            key="portal"
            getContainer={this.getContainer}
            didUpdate={this.handlePortalUpdate}
          >
            {this.getComponent()}
          </PortalComponent>
        );
      }

      if (!popupVisible && autoDestroy) {
        portal = null;
      }
```

Is it really necessary to keep the portal around for SubMenus?  I'd be glad to create a PR for fixing this issue, but I'm not sure what the best solution might be.

**Comment by dfbaskin** [comment]
One option would be to always have the SubMenu auto-destroy:

```diff
--- a/src/SubMenu/PopupTrigger.tsx
+++ b/src/SubMenu/PopupTrigger.tsx
@@ -24,6 +24,7 @@ export interface PopupTriggerProps {
   popupClassName?: string;
   popupOffset?: number[];
   disabled: boolean;
+  autoDestroy?: boolean;
   onVisibleChange: (visible: boolean) => void;
 }

@@ -37,6 +38,7 @@ export default function PopupTrigger({
   disabled,
   mode,
   onVisibleChange,
+  autoDestroy
 }: PopupTriggerProps) {
   const {
     getPopupContainer,
@@ -106,6 +108,7 @@ export default function PopupTrigger({
       onPopupVisibleChange={onVisibleChange}
       forceRender={forceSubMenuRender}
       popupMotion={mergedMotion}
+      autoDestroy
     >
       {children}
     </Trigger>
diff --git a/src/SubMenu/index.tsx b/src/SubMenu/index.tsx
index c86681e..d56b61d 100644
--- a/src/SubMenu/index.tsx
+++ b/src/SubMenu/index.tsx
@@ -290,6 +290,7 @@ const InternalSubMenu = (props: SubMenuProps) => {
         }
         disabled={mergedDisabled}
         onVisibleChange={onPopupVisibleChange}
+        autoDestroy
       >
         {titleNode}
       </PopupTrigger>
```

Thoughts?

**Comment by xsjcTony** [comment]
Same Problem. Is any fix available yet?

**Comment by xsjcTony** [comment]
> One option would be to always have the SubMenu auto-destroy:
> 
> ```diff
> --- a/src/SubMenu/PopupTrigger.tsx
> +++ b/src/SubMenu/PopupTrigger.tsx
> @@ -24,6 +24,7 @@ export interface PopupTriggerProps {
>    popupClassName?: string;
>    popupOffset?: number[];
>    disabled: boolean;
> +  autoDestroy?: boolean;
>    onVisibleChange: (visible: boolean) => void;
>  }
> 
> @@ -37,6 +38,7 @@ export default function PopupTrigger({
>    disabled,
>    mode,
>    onVisibleChange,
> +  autoDestroy
>  }: PopupTriggerProps) {
>    const {
>      getPopupContainer,
> @@ -106,6 +108,7 @@ export default function PopupTrigger({
>        onPopupVisibleChange={onVisibleChange}
>        forceRender={forceSubMenuRender}
>        popupMotion={mergedMotion}
> +      autoDestroy
>      >
>        {children}
>      </Trigger>
> diff --git a/src/SubMenu/index.tsx b/src/SubMenu/index.tsx
> index c86681e..d56b61d 100644
> --- a/src/SubMenu/index.tsx
> +++ b/src/SubMenu/index.tsx
> @@ -290,6 +290,7 @@ const InternalSubMenu = (props: SubMenuProps) => {
>          }
>          disabled={mergedDisabled}
>          onVisibleChange={onPopupVisibleChange}
> +        autoDestroy
>        >
>          {titleNode}
>        </PopupTrigger>
> ```
> 
> Thoughts?

I still want it to hide instead of destroyed. I'm working on a function requiring the DOM element of the popup menu.
Hence if it's destroyed, I cannot get the element.

**Comment by xsjcTony** [comment]
Work around is in #544
