### ISSUE TITLE
服务器端渲染报警告

### ISSUE THREAD

**Issue by htcqp802** [react-component/menu#47]
warning.js:45Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) aria-owns="1469171077731_0" aria-haspopu
 (server) aria-owns="1469171076562_0" aria-haspopu

**Comment by yiminghe** [comment]
可以帮忙看下，我这边看没问题
