### ISSUE TITLE
Issue with using conditional `disabled` attribute on MenuItems

### ISSUE THREAD

**Issue by quicksnap** [react-component/menu#5]
I have a requirement that selected MenuItems should appear disabled. I tried this: 

```javascript
        <MenuItem
          key={id}
          disabled={ id === this.state.selectedId } >
            {menuItemName}
        </MenuItem>
```

This causes issues on this line: https://github.com/react-component/menu/blob/master/lib/Menu.js#L155

since this code causes onDeselect not to be defined: https://github.com/react-component/menu/blob/master/lib/Menu.js#L218-L221

I've disabled the `disabled` check and it seems to fix my menu. Is this premature `return` necessary?

**Comment by yiminghe** [comment]
it's an interesting use case: you can not deselect a selected disabled menuitem

http://react-component.github.io/menu/build/examples/multiple.html

**Comment by quicksnap** [comment]
Thanks for the fix! Curious, why the `concat([])` call here?: https://github.com/react-component/menu/commit/6204eb77f1af18416fa1634edd43633508b5e29d#diff-5fbb3e2b7b0ae90b101ff557be1ad728R186

Are you cloning the `this.state.selectedKeys` to prevent referencing the original state object?

**Comment by yiminghe** [comment]
yes, modify state/props directly is a bad practice (as react 0.13 emphasized), i didn't notice it before.
