### ISSUE TITLE
What does this code mean?

### ISSUE THREAD

**Issue by zhuscat** [react-component/menu#50]
I'm reading the source code of this component. 
I'm puzzled by the following code:
## Problem 1

https://github.com/react-component/menu/blob/master/src/MenuItem.jsx#L78

Why you pass a parameter to `clearMenuItemMouseLeaveTimer` ?
## Problem 2

https://github.com/react-component/menu/blob/master/src/MenuItem.jsx#L140

Isn't `callFn` always `undefined` ?

It will be good if you can help me.

**Comment by benjycui** [comment]
Yep, dead code...

Could you just create a PR to remove them?

cc @yiminghe
