### ISSUE TITLE
Mouse leave behavior change on 4.13+

### ISSUE THREAD

**Issue by pward123** [react-component/menu#51]
The behavior of openSubMenuOnMouseEnter and closeSubMenuOnMouseLeave seems to have changed between 4.12.4 and 4.13.0

Run the antd example at https://github.com/pward123/menu/tree/hover-4.12.4 then click on the horizontal 'submenu' item and slide your mouse back and forth over the two submenu titles.  The dropdown should stay open.

Try the same thing with https://github.com/pward123/menu/tree/hover-5.0.0.  The submenu will close when your mouse moves across the title boundary.

I'd like the user to click on the title to open a submenu, but want the behavior of 4.12.4 when the user is moving between submenus.

The code that appears to be causing the menu to close is https://github.com/react-component/menu/blob/master/src/MenuMixin.js#L172.

**Comment by benjycui** [comment]
Actually, an online demo will be better...

And how about the behavior in rc-menu@5.x? For we are not going to maintain rc-menu@<=4.x

**Comment by pward123** [comment]
5.x has the problem as well. I mentioned 4.13.0 because that's where I determined the problem was introduced.

**Comment by benjycui** [comment]
OK, I understand, could your provide an online demo with `5.x`?

**Comment by benjycui** [comment]
Close for no response.
