### ISSUE TITLE
SubMenu does not work with Universal/Isomorphic apps

### ISSUE THREAD

**Issue by andreme** [react-component/menu#52]
Due to the automatically generated Menu ID for aria-owns, server and client generate different html:

> vendor.js?cacheHash=919053d…:38404 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
>  (client) aria-owns="1474721378027_0" aria-haspopu
>  (server) aria-owns="1474721377705_1" aria-haspopu

As a quick way to fix this I was thinking it should be possible to add an optional AriaID or MenuID property that gets used if set, otherwise it will still be auto generated like it is now?

**Comment by yiminghe** [comment]
https://github.com/react-component/menu/commit/551143f45175169d41e04389d4d48458e08985c3
