### ISSUE TITLE
SubMenu使得服务端和客户端render的html不一致

### ISSUE THREAD

**Issue by xpcode** [react-component/menu#55]
https://github.com/react-component/menu/blob/master/src/SubMenu.jsx

render函数里的
 this._menuId = this._menuId || guid();
在服务端渲染和客户端渲染会生成不同的html，使得做同构应用时客户端需要重复渲染，希望能把guid()换成一个客户端和服务端保持一直的字符串

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2061
https://github.com/ant-design/ant-design/issues/2406
https://github.com/ant-design/ant-design/issues/3293

感谢反馈，终于找到上面这些问题的原因了~

**Comment by xpcode** [comment]
那你不来实际点的感谢 @afc163 哈哈

**Comment by afc163** [comment]
来个 PR 修复此问题，我给你寄个部门内用的纪念杯子~ 👊🏻

**Comment by xpcode** [comment]
就这么定了

**Comment by xpcode** [comment]
就这么定了，没有环境，未跑测试啊

https://github.com/react-component/menu/pull/56

**Comment by afc163** [comment]
closed in https://github.com/react-component/menu/pull/56

现在需要在前后端指定 eventKey `<Menu.Item key={1} eventKey={1} />`。

@xpcode 虽然没有合并你的代码，但是杯子还是会寄给你的，把地址和电话邮件给我吧~

**Comment by yiminghe** [comment]
eventKey 不需要

**Comment by xpcode** [comment]
本来是开玩笑的，既然给我一个就不客气了啊。
地址：北京市昌平区6环内平西府地铁口公园悦府小区1号楼3单元2202
姓名：陈黄方


发自我的 iPhone

**Comment by afc163** [comment]
@xpcode 单独邮件给我，你这么发信息都泄漏了呀，我给你删掉了。

**Comment by xpcode** [comment]
谢谢啊，没注意这个，哈哈

地址：北京市昌平区6环内平西府地铁口公园悦府小区1号楼3单元2202
姓名：陈黄方


发自我的 iPhone

**Comment by afc163** [comment]
你又发出来了。。。。

**Comment by xpcode** [comment]
现在需要在前后端指定 eventKeyMenu.Item key={1} eventKey={1} /




这样不能解决问题，需求是：


同一个页面使用多个SubMenu时，每个实例的_menuId不同；但同一个SubMenu在每次render时_menuId却相同。


原始邮件
发件人:偏右notifications@github.com
收件人:react-component/menumenu@noreply.github.com
抄送:C.4019980@qq.com; Mentionmention@noreply.github.com
发送时间:2016年10月17日(周一) 11:51
主题:Re: [react-component/menu] SubMenu使得服务端和客户端render的html不一致 (#55)


closed in #56
现在需要在前后端指定 eventKey Menu.Item key={1} eventKey={1} /。
@xpcode 虽然没有合并你的代码，但是杯子还是会寄给你的，把地址和电话邮件给我吧~

**Comment by afc163** [comment]
不需要指定 eventKey 了，直接用的 key 。

**Comment by xpcode** [comment]
sorry，我错了，原来eventKey就是key，换成这样写就没问题了SubMenu key=“submenu” … /






原始邮件
发件人:40199804019980@qq.com
收件人:react-component/menumenu@noreply.github.com; react-component/menureply@reply.github.com
抄送:Mentionmention@noreply.github.com
发送时间:2016年10月17日(周一) 14:50
主题:Re: [react-component/menu] SubMenu使得服务端和客户端render的html不一致 (#55)


现在需要在前后端指定 eventKeyMenu.Item key={1} eventKey={1} /




这样不能解决问题，需求是：


同一个页面使用多个SubMenu时，每个实例的_menuId不同；但同一个SubMenu在每次render时_menuId却相同。


原始邮件
发件人:偏右notifications@github.com
收件人:react-component/menumenu@noreply.github.com
抄送:C.4019980@qq.com; Mentionmention@noreply.github.com
发送时间:2016年10月17日(周一) 11:51
主题:Re: [react-component/menu] SubMenu使得服务端和客户端render的html不一致 (#55)


closed in #56
现在需要在前后端指定 eventKey Menu.Item key={1} eventKey={1} /。
@xpcode 虽然没有合并你的代码，但是杯子还是会寄给你的，把地址和电话邮件给我吧~
