### ISSUE TITLE
Menu 菜单 使用了openKeys属性无法展开二级菜单

### ISSUE THREAD

**Issue by frontend-winter** [react-component/menu#556]
Menu 菜单 使用了openKeys属性无法展开二级菜单
代码图
<img width="476" alt="image" src="https://user-images.githubusercontent.com/48146286/203913443-f4c84e79-76d8-419f-95b5-4a9321ac6874.png">

效果图
![image](https://user-images.githubusercontent.com/48146286/203913596-bc088d34-2c59-4684-9dbf-7337c5b06d73.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/38984#issuecomment-1327100204
