### ISSUE TITLE
expandIcon callback doesn't work

### ISSUE THREAD

**Issue by aistrike01** [react-component/menu#568]
This is my code:

```
<Navigation
      className='mobile-menu'
      inlineIndent={8}
      mode="inline"
      expandIcon={(isOpened) => isOpened ? <SvgIcon type={isOpened ? 'openIcon' : 'closeIcon' }> }
      openKeys={openKeys}
      onOpenChange={onOpenChange}
      items={footerMobileMenu}
/>
```

I used the callback that is mentioned in the documentation, but isOpened does not work, maybe I don't understand something.

<img width="594" alt="Снимок экрана 2022-12-15 в 11 18 09" src="https://user-images.githubusercontent.com/69678753/207820726-ad13cc2d-fe39-4531-a7b2-e5a1c52fc251.png">

**Comment by rynodivino** [comment]
Hi @aistrike01,

I may be mistaken, but the function provided to `expandIcon` prop in the code snippet you provided doesn't look valid.

It looks like a nested ternary, but afaict there is no false condition on the first.  What is expected to happen if `isOpened` is false.

Maybe it should look more like this:
`expandIcon={(isOpened) =>  <SvgIcon type={isOpened ? 'openIcon' : 'closeIcon' }> }`

**Comment by aistrike01** [comment]
Hi @rynodivino,
You are right, I wrote it wrong
