### ISSUE TITLE
what the relationship between react's props key and rc-menu's props eventKey

### ISSUE THREAD

**Issue by zhangzewei** [react-component/menu#58]
i really can not figure out how you get the react's props key to your menuItem's props eventKey, or where your eventKey can be get.
like this:
```js
<Menu>
    <MenuItem key="m1">一级菜单</MenuItem>
    <SubMenu key="sbm1" title="二级菜单">
        <MenuItem key="sbm1-m1">2级菜单子选项</MenuItem>
        <SubMenu key="sbm2" title="三级菜单">
            <MenuItem key="sbm2-m1">3级菜单子选项</MenuItem>
        </SubMenu>
   </SubMenu>
</Menu>
```
and how the relationship between the key and the rc-menu's props eventKey, because l'm learning making a menu component by modeling your code, may I ask you for a favor?

**Comment by benjycui** [comment]
We just overload the meaning of React's key, you can read the source code for more detail.

**Comment by benwiley4000** [comment]
This is pretty surprising and confusing behavior. I would highly recommend changing this in a future major release. I am still combing through the source code and don't understand.
