### ISSUE TITLE
Click subMenu element gets no responses when set openKeys on Menu element.

### ISSUE THREAD

**Issue by DiscipleD** [react-component/menu#59]
Click `subMenu` element gets no responses when set `openKeys` on Menu element in `inline` mode.

Bug Scene: [jsfiddle](https://jsfiddle.net/Disciple_D/kukx2y7p/)

After digging in source code, i found following code cause the bug on line 163 in /src/menu.jsx

```
  if (!('openKeys' in this.props)) {
    this.setState({ openKeys });
  }
```

It's seems that you don't change the `openKeys` when it's set. That cause the click event not work.

Is there an issue or a special purpose?

**Comment by benjycui** [comment]
Try to think in React https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by DiscipleD** [comment]
Is there meaning I should handle the click event manually to toggle the key in `openKeys` array?

**Comment by starInEcust** [comment]
@DiscipleD 
`
<SubMenu
                        onTitleClick={() => {
                            // 完全手动接管开关
                            const { openKeys } = this.state;
                            let openKeysPresent;
                            if (openKeys.indexOf(listItemConfig.key) > -1) {
                                openKeysPresent = openKeys.filter(key => key !== listItemConfig.key);
                            } else {
                                openKeysPresent = [...openKeys, listItemConfig.key];
                            }
                            this.setState({
                                openKeys: openKeysPresent,
                            });
                        }}
                        key={listItemConfig.key}
                        title={listItemConfig.primaryText}
                    >
                        {listItemConfig.nestedItems}
                    </SubMenu>
`

**Comment by DiscipleD** [comment]
@starInEcust Thanks for your advice.

I had a solution like you before, but I thought it weird to handle click event. It's like a normal requirement toggle the menu element when user click the submenu, and it can be easily implemented.

Maybe I should change my mind.

Thank you again.
