### ISSUE TITLE
menuId 的生成方式无法支持 SSR

### ISSUE THREAD

**Issue by yesmeck** [react-component/menu#63]
https://github.com/react-component/menu/blob/master/src/SubMenu.jsx#L388

在 _menuId 里带上时间戳会让服务端和客户端的渲染结果不一致。

**Comment by benjycui** [comment]
这里好像处理了？ https://github.com/react-component/menu/commit/367daac6a4cc7428098e2603a3310c02f43745f5

确保 `SubMenu[key]` 设置了。

**Comment by yesmeck** [comment]
https://github.com/react-component/menu/commit/367daac6a4cc7428098e2603a3310c02f43745f5#diff-7f8a02620917aa2ed1113e338915793bR388 就是这行有问题啊

**Comment by yesmeck** [comment]
不是确保设置的问题，是 guid 里带了时间戳导致 render 结果不一致。

**Comment by yiminghe** [comment]
https://github.com/react-component/menu/commit/551143f45175169d41e04389d4d48458e08985c3

**Comment by yesmeck** [comment]
发现这里还有个用了时间的 https://github.com/react-component/menu/blob/master/src/util.js#L10

**Comment by yiminghe** [comment]
pr
