### ISSUE TITLE
clone到本地后无法打包，npm run compile后报错，No files matching the pattern "error"" were found.Please check for typing mistakes in the pattern.

### ISSUE THREAD

**Issue by bbb169** [react-component/menu#659]
![T9{IKCJDOYCYWSE}UQ8((DQ](https://github.com/react-component/menu/assets/102608263/8dbab43e-ad94-411e-8622-82b07f410991)

您好我想调试这个组件并打包出来，然后开发ant-design的时候yarn link到这个包上，但是出现了无法打包的情况，请问我应该怎么做呢

**Comment by yoyo837** [comment]
用`npm run compile`, `now` 是一个部署服务

**Comment by yoyo837** [comment]
我记得我评论前试过OK的，明天上午我再试试

**Comment by bbb169** [comment]
> 我记得我评论前试过OK的，明天上午我再试试

好的麻烦啦

**Comment by yoyo837** [comment]
![image](https://github.com/react-component/menu/assets/6134547/f9abb43c-1600-4c36-b1e5-b3cbbeb5232d)

![image](https://github.com/react-component/menu/assets/6134547/2e4da01a-d68e-401a-86be-f6c93565b3d6)

确实可以

**Comment by bbb169** [comment]
> ![image](https://user-images.githubusercontent.com/6134547/250701665-f9abb43c-1600-4c36-b1e5-b3cbbeb5232d.png)
> 
> ![image](https://user-images.githubusercontent.com/6134547/250701683-2e4da01a-d68e-401a-86be-f6c93565b3d6.png)
> 
> 确实可以

可以给一下node版本和eslint版本嘛，我在另一台电脑上试过后发现也不能进行打包

**Comment by bbb169** [comment]
> 以给一下node版本和eslint版本嘛，我在另一台电脑上试过后发现也不能进行打包
项目下载下来以后我是先进行yarn，然后yarn compile

**Comment by yoyo837** [comment]
node, v16.20.1, eslint由源码决定的

**Comment by yoyo837** [comment]
我用yarn 1.x 也是成功的

**Comment by bbb169** [comment]
> 我用yarn 1.x 也是成功的

![image](https://github.com/react-component/menu/assets/102608263/1031507d-6702-42fc-a631-6e53208b447c)
我好像不太行

**Comment by bbb169** [comment]
> 我用yarn 1.x 也是成功的

我发现不止这个项目，其它react-component的组件我也都打包不了哈哈

**Comment by yoyo837** [comment]
试试不用powershell用cmd

**Comment by bbb169** [comment]
> 

好的我试下，跟npm版本有关系嘛，我这边是9.6.4

**Comment by bbb169** [comment]
![image](https://github.com/react-component/menu/assets/102608263/c94dc685-527c-451e-8ce2-76f456246448)

**Comment by yoyo837** [comment]
> > 
> 
> 好的我试下，跟npm版本有关系嘛，我这边是9.6.4

你用 yarn 的话应该和 npm 没关系吧?

**Comment by bbb169** [comment]
> > > 
> > 
> > 
> > 好的我试下，跟npm版本有关系嘛，我这边是9.6.4
> 
> 你用 yarn 的话应该和 npm 没关系吧?

也是，但我两边都用了下

**Comment by yoyo837** [comment]
你只在明亮行下运行 和setting.json没关系

**Comment by bbb169** [comment]
![image](https://github.com/react-component/menu/assets/102608263/90dc68c5-9f3c-4f11-9a64-12ebb52a0167)
npm start也会失败
