### ISSUE TITLE
Menu chokes when passed a child of ''

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [react-component/menu#67]
See the line ` {(Meteor.userId()) ? '' : <MenuItem key="/signup">Join</MenuItem>}`

I took a quick look at the source and did not see anything obvious. I will dig deeper latter as for now I fixed it with the following `{(Meteor.userId()) ? <MenuItem key="/logout"></MenuItem> : <MenuItem key="/signup">Join</MenuItem>}` Which shows up as a 2px high menu item that you cant see unless you hover over it. Reminds me of that move 'The Net' :grinning: 

    export const MainMenuComp = ({list}) => {
      let items = list.map((item) => <MenuItem key={item.url}>{item.name}</MenuItem>);
      items.unshift(<Divider key="divider"/>);
      items.unshift(<MenuItem key="/createshow">Added A New Show</MenuItem>);

      return (
        <Menu className="main-menu" onSelect={handleSelect} onOpen={console.log} mode="horizontal">
          <MenuItem key="/">Home</MenuItem>
          <SubMenu title={<span>Categories</span>} key="categories" mode="vertical">
            {items}
          </SubMenu>
          <SubMenu title={<span>My Account</span>} key="myaccount" mode="vertical">
            <MenuItem key="/myshows">My Shows</MenuItem>
            <MenuItem key="/createshow">Added A New Show</MenuItem>
            <MenuItem key="/createepisode">Added A New Episode</MenuItem>
          </SubMenu>
          <MenuItem key="/community">Community</MenuItem>
          <MenuItem key="/faqs">FAQs</MenuItem>
          {/* todo fix this better - issue menu does not like having '' as a menu item */}
          {(Meteor.userId()) ? '' : <MenuItem key="/signup">Join</MenuItem>}
        </Menu>
      )
    };

**Comment by benjycui** [comment]
Why not:

```jsx
{(Meteor.userId()) ? null : <MenuItem key="/signup">Join</MenuItem>}
``

**Comment by MichaelLeeHobbs** [comment]
Nope chokes on that too.

**Comment by yesmeck** [comment]
`Menu` and `Menu.SubMenu` only accepts  `Menu.SubMenu` `Menu.Item` as children.

**Comment by MichaelLeeHobbs** [comment]
I guess you could consider this as an improvement request then, the ability to accept null/undefined/''.

**Comment by benjycui** [comment]
@MichaelLeeHobbs try the latest version, see: https://github.com/react-component/menu/pull/70/files

**Comment by MichaelLeeHobbs** [comment]
@benjycui Works great, thanks!
