### ISSUE TITLE
openKeys becomes undefined in Menu.componentWillReceiveProps

### ISSUE THREAD

**Issue by williamkhshea** [react-component/menu#74]
I have got a SubMenu like this:
```
      <div>
        <Menu mode="horizontal" id="nav">
          <SubMenu title="John">
            <MenuItemGroup key="actions" title="Actions">
              <Menu.Item key="createCompany">
                <a href="#" >Create Company</a>
              </Menu.Item>
              <Menu.Item key="signOut">
                <a href="#" >Sign Out</a>
              </Menu.Item>
            </MenuItemGroup>
          </SubMenu>
        </Menu>
      </div>
```

For some reason it triggers the componentWillReceiveProps immediately after it first render, and openKeys is undefined in nextProps so it passes on causing an error in isOpen in SubMenu
<img width="926" alt="screen shot 2017-01-22 at 5 09 43 am" src="https://cloud.githubusercontent.com/assets/4775489/22177831/07038dd4-e061-11e6-9e36-6fe163d7f8b3.png">

I spent a couple of hours and still cannot reproduce in it online. Adding a guard clause against undefined openKeys (and for selectedKeys, just in case) should solve the issue.

I will submit a PR now.

**Comment by mmacedoeu** [comment]
I have a similar problem with undefined openKeys:
http://codepen.io/mmacedoeu/pen/EZrpdX

How can I test your solution ?

**Comment by benjycui** [comment]
@mmacedoeu sorry, it seems that your CodePen is broken.

And you can try to upgrade to the latest rc-menu.
