### ISSUE TITLE
菜单变化时 defaultOpenKeys 被修改

### ISSUE THREAD

**Issue by lomocc** [react-component/menu#77]
当菜单内容（children）被修改时 defaultOpenKeys 也被删除了
相关代码：
```js
// Menu.jsx line 69
onDestroy(key) {
  // ...
  selectedKeys.splice(index, 1);
  openKeys.splice(index, 1);
}
```
为什么要这么做，并且是直接 _splice_ ?
另外项目依赖 PhantomJS， 想编译一下都不知道如何入手。

**Comment by benjycui** [comment]
这里的确不好处理，或者需要讨论一下，当 `defaultOpenKeys|openKeys` 依赖的 children 被 destroy 了，应该触发一个 `onOpenChange` 事件还是直接悄悄的改动？

**Comment by benjycui** [comment]
或者什么都不做？毕竟 destroy 是 developers 的决定，他们应该自行处理？

**Comment by lomocc** [comment]
感谢回复，我的理解是：
- defaultProps 应该伴随着组件实例创建直到销毁。**不应该有人可以中途修改这个值**，就算要修改也是修改本实例中他的拷贝。
- destroy 是 developers 的决定，但是修改应该只能影响到实例本身。
- 如果开发者有根据 children 同步 openKeys 的需求，应该使用新的 openKeys 传入。

**Comment by benjycui** [comment]
Ref: https://github.com/react-component/menu/blob/d7048ed1eda88950dc03bf526cfcd526d5a644b7/src/Menu.jsx#L73-L86

还在重构 rc-menu，暂时就保持原样吧。

**Comment by tstrilogy** [comment]
遍历时候key,menuItem的key 和 react 的要求的key重复了吧？react 会利用这个key属性进行页面渲染，为什么你们也会使用这个key ，导致现在map 不能遍历了啊
