### ISSUE TITLE
Setting id on Menu.Item

### ISSUE THREAD

**Issue by fgiarritiello** [react-component/menu#80]
Is it possible to set the id on Menu.Item?
This doesn't seem to work

`<Menu.Item id="edit-profile-link" key={1}>Edit Profile</Menu.Item>`

**Comment by benjycui** [comment]
You cannot, and I don't understand why you need to do so?

**Comment by fgiarritiello** [comment]
Sorry, you are right, the id goes on the <a> inside the Menu.Item. I need the id so that QA can access the dom directly. Closing.
