### ISSUE TITLE
能否给 menu.item 增加“是否保留选中状态”开关?

### ISSUE THREAD

**Issue by leadream** [react-component/menu#84]
hello,
我在使用 Antd 的 Dropdown 组件时，有这么一种情形：鼠标移到触发按钮上->下拉菜单出现->点击某一项 menu.item ->弹出模态框->鼠标移走->点击的 menu.item 仍处于选中状态。

在这种情形下，menu.item 不再是导航链接的角色，而是一个触发按钮的角色，鼠标移走之后应该去掉 selected 状态。 所以我在想能不能给 menu.item 组件添加一个属性 deselectOnMouseLeave ，默认为 false ，当设置为 true 时鼠标移走就移除 selected 状态。

**Comment by afc163** [comment]
`selectedKeys={[]}` 即可。
