### ISSUE TITLE
当Menu处于右侧，mode为vertical时，弹出菜单跑屏幕外去了

### ISSUE THREAD

**Issue by vipcxj** [react-component/menu#85]
可不可以增加一个prop，设置弹出菜单的方向可以为left或right

**Comment by paranoidjk** [comment]
给个 demo ？

**Comment by vipcxj** [comment]
https://ant.design/components/layout-cn/
就是这个侧边布局，例子中Sider是在左侧，我想放到右侧，Sider展开时效果不错，但关闭后就杯具了，用react-tool调试，发现Menu的mode确实从inline变成vertical了，但弹出的子菜单仍旧从Submenu的右侧弹出。然而Submenu的右侧显然是没空间的，于是结果就是看不到弹出的菜单，并且还会在右侧出现滚动条，因为父级div被顶大了~

**Comment by paranoidjk** [comment]
> 给个 demo ？

demo means code

**Comment by vipcxj** [comment]
https://github.com/vipcxj/ant-design
branch: patch-1
site: http://127.0.0.1:8001/components/layout-cn/
侧边布局

**Comment by benjycui** [comment]
Duplicate: https://github.com/react-component/menu/issues/53

Trace: https://github.com/react-component/menu/issues/19

**Comment by vipcxj** [comment]
意思是用第三方库解决吗？
