### ISSUE TITLE
Close menu after click on any menu item

### ISSUE THREAD

**Issue by straiks** [react-component/menu#89]
Hello all,
i know, this is a duplicate, but i have really hard time to make intdl menu to close, after i click on open menu item. Can anyone help me with this?

**Comment by natkuhn** [comment]
I am appreciating this package, but I am not seeing an answer to this question, and I am not seeing it in any of the examples.  Please document!

Also would like some documentation of how to style the menus.

But thanks for the work on the package!

**Comment by benjycui** [comment]
> Hello all,
> i know, this is a duplicate, but i have really hard time to make intdl menu to close, after i click on open menu item. Can anyone help me with this?

Please provide more detail, I don't understand what you said.

**Comment by Utzel-Butzel** [comment]
The currently opened SubMenus can be set via the `openKeys` prop

I handled the `openKeys` prop on via the `activeKey` state:

```
constructor(props) {
    super(props);
    this.state = {
      activeKeys: [],
      open: false
    };
  }
```

Update activeKey once there is a change:

```
  onOpenChange = (openKeys) => {
    this.setState({ 
      activeKeys: openKeys
    });
  }
```
Use activeKey as openKeys
`<Menu openKeys={this.state.activeKeys}>`

Now you can close all items from any point
```
  onClick = (e) => {
    this.setState({ 
      activeKey: false
    });
  }
```


```
<SubMenu onTitleClick={this.onClick}>
...
</SubMenu>
```

**Comment by benjycui** [comment]
Close for no response.

@straiks just follow @Utzel-Butzel advice, if you meet any problem, please provide more information.

**Comment by bburns** [comment]
A more complete example following @Utzel-Butzel 's approach, using hooks - 

```
export default function ({ history }) {

  const [activeKeys, setActiveKeys] = React.useState([])

  function handleClick({ key }) {
    setActiveKeys([]) // close the menu on click
    history.push(key)
  }

  function onOpenChange(openKeys) {
    setActiveKeys(openKeys)
  }

  return (
    <span className="menu">
      <Menu
        mode="horizontal"
        openAnimation="slide-up"
        onClick={handleClick}
        onOpenChange={onOpenChange}
        openKeys={activeKeys}
      >
        <SubMenu title="" key="submenu">
....
```
