### ISSUE TITLE
MenuItem in a functional component breaks in JSX...

### ISSUE THREAD

**Issue by natkuhn** [react-component/menu#91]
...but works otherwise.

Minimal example attached, which I used under create-react-app for setup.

It work as is, but if you replace "{Item()}" with "<Item />", it does not.

Here is the code:

```
import React, { Component } from 'react';
import Menu, { SubMenu, Item as MenuItem, Divider } from 'rc-menu';
import 'rc-menu/assets/index.css';

/*BUG:
        {Item()} works but
        <Item /> does not
*/

class App extends Component {
  render() {
    return (
      <Menu>
        {Item()}
      </Menu>
    );
  }
}

function Item() {
  return (
    <MenuItem key="size">Bug report</MenuItem>
  );
}

export default App;
```

**Comment by benjycui** [comment]
It's an known issue, and it's impossible to fix, unless we change the API.

**Comment by chj-damon** [comment]
@benjycui does this also mean that I cannot use HOC to wrap Menu.Item？such as for authentication?

**Comment by benjycui** [comment]
@chj-damon yes, it is.

**Comment by oliver-ni** [comment]
@benjycui I know this is old, but is there any reason this is the case? This is a very common use case and I am trying to figure out if there would be any workaround to get HOC to work.
