### ISSUE TITLE
version 5.1.0 using Font Awesome from unsecure CDN

### ISSUE THREAD

**Issue by oferitz** [react-component/menu#96]
https://github.com/react-component/menu/commit/163dfeb3d1a9c442705af570c233c3499293ed6f#diff-0e1130f84eefdbec26836cf3da534eb4

Please consider not taking font-awesome from CDN but to serve it locally.
But if you must use CDN then please change to
https://cdn.bootcss.com/font-awesome/4.2.0/fonts/fontawesome-webfont.eot?v=4.2.0
as websites that are under `https://` and depend on rc-menu will get mixed content error and the font cannot be served because the request is blocked.

**Comment by benjycui** [comment]
Yep, PR is welcomed, you can update `http` to `https`, thanks 😄

**Comment by andreysaleba** [comment]
Hey, I've added the PR with this change

**Comment by Shubhasis10** [comment]
https://www.belpahari.co.in
